### ISSUE TITLE
Help Wanted❗️💰

### ISSUE THREAD

**Issue by w0lfschild** [MacEnhance/MacForge#16]
A few things I need support with for this project and am likely willing to pay some small amount for meaningful assistance with:

High priority :

- [ ] Website for browsing / installing plugins
- [ ] Support on backend development ([Firebase](https://firebase.google.com/))

Medium priority :

- [ ] Security improvements
- [ ] Code cleanup / Refactoring

Low priority :

- [ ] Translations

Done 

- [x] New more professional and cleaner icon set (Dock and menubar)

You can also check out the [Projects page](https://github.com/w0lfschild/MacForge/projects/1) for a basic 1.0 roadmap.

**Comment by kingtosh** [comment]
Please tell me icons specifications you need, maybe i could assist for icons.

**Comment by w0lfschild** [comment]
@kingtosh 

For sizing:
- https://iconhandbook.co.uk/reference/chart/osx/

For the menubar:

- Preferably very similar or the same design as the main app icon

For the main app icon:

- Vector image if possible
- Preferably the logo would be inside a circular border with a gradient background similar to the app store icon or many other stock apps.

![appstore](http://www.myiconfinder.com/uploads/iconsets/128-128-21cabddae0ef1e593f7d11a4262a3ec9-appstore.png) ![ibooks](http://www.myiconfinder.com/uploads/iconsets/128-128-484c651b12ef88bbaca53f839fa2725c-ibooks.png) 
- Preferably the logo would be simple with a minimal amount of complexity.
- Preferably the image would be based around either

Forging something eg. 
![hammer](https://media.xconomy.com/wordpress/wp-content/images/2018/12/06071710/forgeai-220x147.jpg)
![smith](https://leadershipmindsetblog.files.wordpress.com/2018/08/blacksmith-forge.png)

Or MacOS default KEXT icon
![kext](https://www.tonymacx86.com/data/attachments/332/332328-41805434c917ce3ad8a0ecff7485414c.jpg)

**Comment by w0lfschild** [comment]
New icons have been acquired.

**Comment by npyl** [comment]
Hi! I am interested in helping out with cleanup and probably backed using Firebase.

I currently have some ideas on improving the app.  These are:
- Fixing the `remove` bundle functionality (actually already have it on my branch)
- Synchronisation problems between get / remove because `get` button doesn't wait until bundle has been installed and goes straight into enabling the remove and donate buttons.

**Comment by w0lfschild** [comment]
@npyl 

That's awesome, thanks! Agree that the app needs some refactoring as well.

I've applied all the changes in your branch as well as a few I had already made and I'll be pushing out an update soon.

**Comment by npyl** [comment]
Hey @w0lfschild 
Thanks for merging my patches.
I just rebased and encountered a problem: MacForge starts up, prints a lot "hol up" messages and doesn't respond to Remove and Donate.

**Comment by w0lfschild** [comment]
@npyl 

- Pretty sure I unlinked both the remove and donate button in the latest build. 😅
- "hol up" was just me doing some testing as a few users were getting an error 

`Assertion failed: (c != nil), function +[MFInjectorProxy injectPID:::], file /Users/w0lf/GitHub/wb_MacForge/MacForge/MacForgeHelper/MFInjectorProxy.m, line 19` 

- Just change this line to `if (c == nil) {`
https://github.com/w0lfschild/MacForge/blob/6a978fac7f79c7c138c489aaf2c315b883e32a82/MacForge/MacForgeHelper/MFInjectorProxy.m#L19

- I had no problems setting up Firebase and getting user accounts set up. It's more of implementing backend features like

    - Star rating system + reviews
    - Linking purchases to accounts
    - Tracking downloads

I just don't really know much about databases and or web specific languages to be able to do that stuff myself.

Currently the code is commented out because adding Firebase to the project just increases compile time and adds like 30MB to the app size so until I have something more meaningful than logining in and out and setting a profile image I just removed the code and frameworks.

As for pay, I'm not really sure but probably a few hundred dollars ideally if someone could kind of teach me a bit about what they end up implementing. I'm also just not really sure of the difficulty of what I'm asking is. I'd honestly imagine it's not too hard if you know what you're doing.

**Comment by npyl** [comment]
Hey
Okay, at some point I realised it must have been a stale debugging thing so I changed `!=` to `==`. 😆 

As for Firebase, I am still interested.  I myself am not very well versed with web stuff though I am willing to take a stub on it.

I will have a look at it these days, actually.
Oh, btw, happy holidays.

**Comment by npyl** [comment]
Hey, 
I've been digging around, learning Firebase and checking-out the code and I have realised I have some questions. First:
1) How do you want the user-related views to work?

I think that the user shown on the sidebar on the left needs to be the one currently signed-in.
If nobody is signed in, then the name should be that of the current OS-user.

On this mindset, there need to be 2 kinds of views:
- Account sign-in (with ability to register a new user)
- Account sign-up (the view that implements the ability mentioned on previous bullet)

Is this how we want to do things?

2. I am a bit confused on how selection of views is implemented.  Which methods are used in for changing the selected view, in particular? 
(I think I will understand sooner or later, anyway)

**Comment by w0lfschild** [comment]
@npyl 

Yeah as you probably noticed I had already made some basic sign in views. 

If you actually go back a few versions of MacForge before I disabled the account tab you could already create / sign in and out / update an account but since it served no purpose not a single person did.

As I said earlier

> Currently the code is commented out because adding Firebase to the project just increases compile time and adds like 30MB to the app size so until I have something more meaningful than logining in and out and setting a profile image I just removed the code and frameworks.

As for what you've done. It seems fine so far.

- Trying to add a picture crashed the app if I cancelled and then I wasn't able to get back to that screen again.
- The views don't seem to be lining up right

**Comment by bermudalocket** [comment]
@w0lfschild Hope you don't mind if I piggyback off your conversation here. I am interested in helping with cleanup as a means to getting more familiar with obcj and swift. I'm not sure I could contribute anything terribly useful but there are a few GUI tweaks I have in mind. Mostly minor annoyances that I've come across, such as not being able to see the full description on the update tab.

I'm running into an issue trying to build the project after a clean clone:
```error: Build input file cannot be found: '/Users/bermudalocket/git/MacForge/MacForge/MacForge/GoogleService-Info.plist' (in target 'MacForge' from project 'MacForge')```

Unfortunately I'm not familiar with Firebase. A quick search led me to a Firebase documentation page mentioning that you have to sign in to your Firebase account to download said plist file... which can't be right? So now I'm here!

**Comment by w0lfschild** [comment]
@bermudalocket 

Removing the GoogleService-Info.plist should be fine.

**Comment by w0lfschild** [comment]
@npyl 

Just pushed out a commit that implements some of your stuff from your dev branch in the way I envision the account view working.

**Comment by npyl** [comment]
@w0lfschild 
Ηey, I checked it out and I like your changes; I think we should keep them.

Some improvements:
One thing to mention, there is no way to set the `username` and the photo (`photoURL`) of the user.
This causes a crash on startup after creation of a user.

Other than that, it's pretty nice.
I am currently giving a look at Firestore.  It seems really easy and uses the NoSQL scheme.

**Comment by npyl** [comment]
@w0lfschild 
Hey
I checked it out.
I liked the design but I think there needs to be some kind of changes related to user creation.

I find it more convenient to be able to directly set the `username` and user `photo` through the `Αccount Sign In` view.
I don't find it practical to have to go to `User Info` and then `Update`.
That's only an idea though.  :)

**Comment by w0lfschild** [comment]
@npyl 

I don't mind having user name a photo assigned at creation but they're also unnecessary and can just be the user profile name and icon by default.

Answer 1.1
I'm not sure about syncing functionality but certainly I think it would be nice to keep track of purchases and be able to download them from the account view.

Answer 2
Right now I don't think there is any reason to put in work relating to multiple users on one computer because the number of instances of that are probably close to or equal to 0.

**Comment by npyl** [comment]
Okay @w0lfschild ,

When it's done, I will send you a video showing the result.

Finally, If you decide that you like my work I will publish half of the end-project on Github (Ratings & Reviews support) and will expect a 50% payment of the reward.

I will publish the rest (and final) 50% (Purchases support) after the 1st payment.

I guess we could start talking about the reward when you see the video (?).

I will also provide support (without reward) for any problem that comes up with my code upon soon notice.

I am not sure if you like my terms; please tell me if anything better comes to mind, I'm generally open to proposals.

Thanks for the cooperation,
Nick

**Comment by w0lfschild** [comment]
@npyl 

Do you have discord or some other way of instant messaging instead of conversing through this issue?

**Comment by npyl** [comment]
@w0lfschild 
Sure, my tag is `npyl#8111`

**Comment by w0lfschild** [comment]
@npyl 

Sent you a friend request.

**Comment by luixiuno** [comment]
@w0lfschild So you ve now helped me, now its time i help you, i can probably be a part of this: Website for browsing / installing plugins

**Comment by luixiuno** [comment]
@w0lfschild i can probably also help a bit with this: Translations

**Comment by luixiuno** [comment]
Your website might be ready (ETA not known) I can make it at MacForge.github.io/Browse-Plugins/

**Comment by luixiuno** [comment]
Translations i know are: A bit of portuguese, a lot of english, and tons of spanish, i can also use google translate

**Comment by w0lfschild** [comment]
Well thanks for the offers.

At the current time I'm not sure about translations until I get the majority of the 1.0 design squared away.

In terms of web-design though, yeah I could use help with that. Basically I'd like to have a page of all the plugins generated from https://github.com/MacEnhance/MacForgeRepo/blob/master/repo/packages.plist

**Comment by luixiuno** [comment]
sure, i will make a cool webpage hosted by: Github Pages im sorry if the repo will have an addres you dont want, i have a repo already with the name of: luixiuno.github.io for cydia, its beta, it almost always breaks cydia

**Comment by luixiuno** [comment]
Ok So That Package List Is SOOOOO long, ik what to do

i need a link to open the app so then, its like you go to my website then click redirect to package and then: open in MacForge

**Comment by luixiuno** [comment]
If you want a website hosted by me, you can just ask at github or at: luixiuno@gmail.com

**Comment by luixiuno** [comment]
Hey wolfgang, i might later have a pre-built version of the beta of MacForge, signed with paid macOS cert

**Comment by luixiuno** [comment]
im in such a big rush: luixiuno.github.io/Screen Recording 2020-07-30 at 18.37.30

**Comment by luixiuno** [comment]
theres a problem with a cocoa thing, put it on do not embeed to solve

**Comment by luixiuno** [comment]
how do i fix: Pods_com_macenhance_MacForge_Injector ld: framework not found Pods_com_macenhance_MacForge_Injector
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by luixiuno** [comment]
Ld /Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Products/Debug/com.macenhance.MacForge.Injector normal x86_64 (in target 'com.macenhance.MacForge.Injector' from project 'MacForge')
    cd /Users/luixiuno/Documents/MacForge/MacForge
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Products/Debug -F/Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Products/Debug -filelist /Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Intermediates.noindex/MacForge.build/Debug/com.macenhance.MacForge.Injector.build/Objects-normal/x86_64/com.macenhance.MacForge.Injector.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Intermediates.noindex/MacForge.build/Debug/com.macenhance.MacForge.Injector.build/Objects-normal/x86_64/com.macenhance.MacForge.Injector_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -sectcreate __TEXT __info_plist MacForgeInjection/Injector-Info.plist -sectcreate __TEXT __launchd_plist MacForgeInjection/Injector-Launchd.plist -Wl -undefined dynamic_lookup -framework Carbon -framework Foundation -framework Pods_com_macenhance_MacForge_Injector -Xlinker -dependency_info -Xlinker /Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Intermediates.noindex/MacForge.build/Debug/com.macenhance.MacForge.Injector.build/Objects-normal/x86_64/com.macenhance.MacForge.Injector_dependency_info.dat -o /Users/luixiuno/Library/Developer/Xcode/DerivedData/MacForge-ailfjyjtznftnjbiiwqtdgwziirm/Build/Products/Debug/com.macenhance.MacForge.Injector

**Comment by w0lfschild** [comment]
Ah yeah you'll need to open terminal and go

```
cd .../MacForge/MacForge
pod update
```

Replacing `.../` with the path to MacForge source folder

**Comment by luixiuno** [comment]
> Ah yeah you'll need to open terminal and go
> 
> ```shell
> cd ~/Documents/MacForge/MacForge
> pod update
> ```

Ill Try That THANK YOU SO MUCH, I ALWAYS KNEW macOS big sur JAILBREAKING WAS POSSIBLE!

**Comment by luixiuno** [comment]
do i need to download CocoaPods?

**Comment by luixiuno** [comment]
If you want me to share the beta of MacForge the ETA might be 30/31 jul

**Comment by luixiuno** [comment]
Uh? where does xcode save the build?

**Comment by luixiuno** [comment]
Great :) , more errors

**Comment by w0lfschild** [comment]
@luixiuno 

> If you want me to share the beta of MacForge the ETA might be 30/31 jul

No

> Where does Xcode save the build?

Depends, you can set it up to build to anywhere. By default it saves to:
`~/Library/Developer/Xcode/DerivedData/<ProjectName>-<RandomString>/Build/Products/Debug/<BuildName>`

> Great, more errors

Not sure what to say, looks like an issue with pods, you have to close and re-open the project after fetching pods. You might also get those issues from using the `.xcodeproj`, you should be opening the `.workspace` instead.

> Why is there no beta downloads?

Because I'm not ready to release any...?

**Comment by luixiuno** [comment]
@wolfschild hw did you just build it but i cant, sorry but im just a kid, idk how to code swift, well, i can edit some .plists and make simple webpages, but im lost idk what to do.

**Comment by luixiuno** [comment]
im afraid that if i make too much tries and delete that Cocoa framework, maybe all my work in that would need to be started again

**Comment by luixiuno** [comment]
> @luixiuno
> 
> > If you want me to share the beta of MacForge the ETA might be 30/31 jul
> 
> No
> 
> > Where does Xcode save the build?
> 
> Depends, you can set it up to build to anywhere. By default it saves to:
> `~/Library/Developer/Xcode/DerivedData/<ProjectName>-<RandomString>/Build/Products/Debug/<BuildName>`
> 
> > Great, more errors
> 
> Not sure what to say, looks like an issue with pods, you have to close and re-open the project after fetching pods. You might also get those issues from using the `.xcodeproj`, you should be opening the `.workspace` instead.
> 
> > Why is there no beta downloads?
> 
> Because I'm not ready to release any...?

it looks like a missing file, or xcode doesnt have perms to enter the folder cause its system´s

**Comment by luixiuno** [comment]
OH MY, THE WORKSPACE HAS A LOT MORE OF THINGS it may work, thanks ;) !

**Comment by luixiuno** [comment]
i wish we could do a call or something but not in discord, thats grownup

**Comment by luixiuno** [comment]
English: MacForge an awesome package manager! Spanish: MacForge un administrador de paquetes increible!

**Comment by luixiuno** [comment]
i need answers

**Comment by luixiuno** [comment]
Is Wolfgang even online?

**Comment by w0lfschild** [comment]
I truly appreciate your enthusiasm, I'm just not sure I can help you build it. It's hard to tell what's going on another persons computer.

Would you just like me to build a copy for you or are you more interested in building it yourself?

**Comment by luixiuno** [comment]
I’m interested to build it myself cause, I’m a genius boy and I never compiled a program :)

**Comment by w0lfschild** [comment]
Maybe try this: https://stackoverflow.com/a/55086382

**Comment by luixiuno** [comment]
Yes, I’m tryna make my own version of brew.sh

**Comment by luixiuno** [comment]
Sorry if I’m flooding the chat but if people are wanting to compile and have errors then they watch this

**Comment by luixiuno** [comment]
ok i need a copy, if you could make a copy for me then put it in a link then after some secs delete the comment

**Comment by luixiuno** [comment]
Have you put the link?

**Comment by luixiuno** [comment]
Does The Webpage Have To Look Modern?

**Comment by luixiuno** [comment]
So, I need a copy for my Big Sur, not hackintosh

**Comment by luixiuno** [comment]
Anybody here?

**Comment by w0lfschild** [comment]
You're loosing me here @luixiuno 

> Yes, I’m tryna make my own version of brew.sh plugin searcher, i changed my mind, imma ma ke a webpage like nito TV website, please give me a link like, Macforge://redirect-to-tweak name
here or tweak ID <-- EDIT please build this

I'm not sure what you mean? 
You can already link to bundles in MacForge https://github.com/MacEnhance/MacForge/wiki/Bundles-:-Linking
What's nito.tv or brew.sh got to do with any of this?

> Ok I need a copy, if you could make a copy for me then put it in a link then after some secs delete the comment

Are you asking for a copy of MacForge built for Big Sur?

> Does The Webpage Have To Look Modern?

What does that even mean? If you're asking if I just want a webpage of plain `.html` with no styling then the answer is no. I'm not sure if you're aware but I already have my own website https://www.macenhance.com/

> So, I need a copy for my Big Sur, not hackintosh

I don't know what this is referring to

> Anybody here?

Please stop spamming, it wont make me respond any faster.

**Comment by luixiuno** [comment]
Deleted comments, I need a fresh copy of the app, that's all I will say, imma delete all

**Comment by luixiuno** [comment]
Did not mean to spam

**Comment by w0lfschild** [comment]
[MacForge.zip](https://github.com/MacEnhance/MacForge/files/5011506/MacForge.zip)

**Comment by luixiuno** [comment]
THANKS A LOT THAT MEANS A LOT TO ME :)

**Comment by luixiuno** [comment]
I need help at disabling AMFI Apple Mobile File Integrity

**Comment by luixiuno** [comment]
OK CCDOCK IN MACOS 11.0 IT CORRUPTS DOCK, i fixed it but dont do it

**Comment by w0lfschild** [comment]
Don't turn off AMFI.

Instead you should disable Library Validation.

Copy pasted from Discord:

Important message!

If you are currently using MacForge and have turned off Apple Mobile File Integrity (AMFI) using the command `nvram boot-args="amfi_get_out_of_my_way=1"`

You will not be able to add applications to `System Preferences > Security & Privacy > Privacy`. This can completely prevent some applications form functioning or break critical functionality.

In order to fix this issue, follow the steps below:

open terminal and run the commands
`sudo nvram boot-args=""`
`sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true`
`reboot`

An updated version of MacForge should hopefully be coming out soon™️ with a built in warning and automation of these steps.

**Comment by luixiuno** [comment]
So I disabled everything but AMFI and I can enter the system tab, and the preference bundles don't load

**Comment by w0lfschild** [comment]
What preference bundles?

**Comment by luixiuno** [comment]
I don't know, I can't enter system, mouse cape doesn't appear, idk if it has it, dockmate doesn't appear and WhosTyping also doesn't

**Comment by w0lfschild** [comment]
What? I don't even know what you're saying.

**Comment by luixiuno** [comment]
You might actually never get help, this issue is lonely, and im out

**Comment by w0lfschild** [comment]
@luixiuno No problem, nobody (including yourself) is obligated to help.

I'm well aware I likely won't ever get any meaningful support on the project and that's fine with me. This issue is 2 years old at this point after all.
