### ISSUE TITLE
Flashlight doesn't work

### ISSUE THREAD

**Issue by iAmRenzo** [MacEnhance/MacForge#35]
First of all I didn't disable SIP, I downloaded MacForge, downloaded Flashlight and got rid of MacForge. Why would I download an app to download and use an app?

But anyway, Flashlight doesn't work. I can see the plugins but when I search in Spotlight none of the Flashlight add ons pop up with information. What's going on?

**Comment by w0lfschild** [comment]
> Why would I download an app to download and use an app?

Because MacForge handles the code injection. Some plugins in MacForge are extensive enough that they need their own GUI to allow users to edit settings or expand upon the plugins functionality. At it's core Flashlight is a `plugin` for Spotlight not an app.
