### ISSUE TITLE
How to re-enable library validation?

### ISSUE THREAD

**Issue by havewisdom** [MacEnhance/MacForge#37]
How to re-enable library validation?
thank you

**We** primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter: [![Chat](https://img.shields.io/gitter/room/MacEnhance/MacFroge)](https://gitter.im/MacEnhance/MacForge)
* Discord: [![Chat](https://img.shields.io/discord/608740492561219617)](https://discord.gg/zjCHuew)
* Also have a look at the readme for more information on how to get support:
  https://github.com/w0lfschild/MacForge/blob/master/README.md

**Comment by w0lfschild** [comment]
Open terminal and run 

`sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool false`

Then reboot

**Comment by w0lfschild** [comment]
Also included in the wiki now

https://github.com/MacEnhance/MacForge/wiki/Uninstallation
