### ISSUE TITLE
Open/Save dialog box issues 

### ISSUE THREAD

**Issue by drewauff** [MacEnhance/MacForge#39]
Open and Save dialog box freeze when opened.

How can I add it to the Application Blacklist?

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Gitter: [![Chat](https://img.shields.io/gitter/room/MacEnhance/MacFroge)](https://gitter.im/MacEnhance/MacForge)
* Discord: [![Chat](https://img.shields.io/discord/608740492561219617)](https://discord.gg/zjCHuew)
* Also have a look at the readme for more information on how to get support:
  https://github.com/w0lfschild/MacForge/blob/master/README.md

**Comment by w0lfschild** [comment]
Did you figure out the issue?
