### ISSUE TITLE
MacForge v0.14.2 beta(2846) bug?

### ISSUE THREAD

**Issue by iant333** [MacEnhance/MacForge#42]
## Bug Report

On restart of computer Macforge crashes Boom 3D (Global Delight) v1.3.6

When Macforge is disabled, Boom 3D starts as normal.

**Environment**

- MacForge version: v0.14.2 beta(2846)
- OS version:  macOS 10.15.5
- Plugins: cDock, colorfulSidebar X and ColorMenuItems

**Comment by w0lfschild** [comment]
Add it to the blacklist?

**Comment by iant333** [comment]
Great, thx it solved the problem, many satisfactory restarts.
