### ISSUE TITLE
Is MacForge supporting the latest version of macOS Big Sur?    PS. This is more of a question

### ISSUE THREAD

**Issue by luixiuno** [MacEnhance/MacForge#43]
Hello, I have macOS Big Sur in my computer (not hackintosh) I'm using original macOS version 11.0 latest beta (20A5323l)

so, Is MacForge safe for my Mac? I don't wanna brick it.

**Comment by luixiuno** [comment]
This is a question, not an issue.

**Comment by w0lfschild** [comment]
If you were to build the source code it would work, but the currently released pre-built version does not.

**Comment by luixiuno** [comment]
so it doesnt support?

**Comment by luixiuno** [comment]
id like to try

**Comment by luixiuno** [comment]
does it work on a catalina VM?

**Comment by luixiuno** [comment]
> If you were to build the source code it would work, but the currently released pre-built version does not.

I would also like to know how to compile github open source apps or projects

**Comment by luixiuno** [comment]
Can i compile it VIA xcode by downloading the project then opening it pre compiled?

**Comment by w0lfschild** [comment]
@luixiuno 

> So it doesn't support Big Sur?

Not currently no.

> Does it work on a Catalina VM?

Yes.

> I don't wanna brick my: MacBook Pro (Retina, 13-inch, Late 2013)

This software cannot brick any machine.

> I would also like to know how to compile GitHub open source apps or projects

You'll need Xcode but beyond that this project needs a few changes to compile. You'd need to select your own account for all `Targets` in the `Signing & Capabilities` tab of the project and provide a `GoogleService-Info.plist` which I believe you could just grab out of a precompiled version of the app.

**Comment by luixiuno** [comment]
The currently open source supports 11.0 beta?

because if it does then im compiling it in xcode, Thanks a lot for the info Wolfgang Bird AKA w0ldschild

**Comment by luixiuno** [comment]
> The currently open source supports 11.0 beta?
> 
> because if it does then im compiling it in xcode, Thanks a lot for the info Wolfgang Bird AKA w0ldschild

the auto correct made me type so bad

**Comment by luixiuno** [comment]
Wolfgang Baird AKA w0lfschild

**Comment by w0lfschild** [comment]
@luixiuno 

> The currently open source supports 11.0 beta?

Yes.

![Screen Shot 2020-07-30 at 1 08 15 PM](https://user-images.githubusercontent.com/1920148/88969481-c95bfc00-d265-11ea-8fb5-7940b3374273.png)

**Comment by w0lfschild** [comment]
> Wolfgang Baird AKA w0lfschild

If you're using GitHub in your web-browser you can edit comments by hitting the little pencil button. Also just w0lf is fine, it's my preferred tag but it's not available on many platforms.

**Comment by luixiuno** [comment]
Oh thank you so much, this forum is now closed.
