### ISSUE TITLE
MacForge Plugin Template Not Appearing In Xcode

### ISSUE THREAD

**Issue by biD3V** [MacEnhance/MacForge#44]
## Bug Report

**Current Behavior**
The MacForge Plugin template does not appear in any of the template sections of Xcode

**To Reproduce**
1. Open MacForge
2. Open Xcode
3. Click "Create a new Xcode project" or `File > New > Project...`
4. MacForge Plugin template is not found in any of the sections

**Expected behavior/code**
MacForge Plugin template to appear in macOS templates.

**Environment**
- MacForge version: 1.0.8 (5825)
- OS version: 10.15.6
- Xcode version: 11.7 (11E801a)

**Comment by w0lfschild** [comment]
Took it out because there's no point in including it when `99.999%` of users have no use for it.

You can find it here: https://github.com/MacEnhance/MacForgeRepo/tree/master/templates
