### ISSUE TITLE
Uninstalling MacForge - reversing changes made to MacOS

### ISSUE THREAD

**Issue by jtn99994** [MacEnhance/MacForge#45]
I installed MacForge and it instructed me to make some changes to my system (partially disabling system integrity protection). I started following the steps but then I realized I was in over my head - I am not a programmer and I don't want to cripple my system's built in security just to install an app.

However, there are no instructions anywhere on how to reverse these changes made in Terminal. Since I followed some of the steps, my OS is now compromised and I don't know how to undo this. I believe there should be instructions for this for the non-programmers like myself (probably in the Uninstall article which mentions nothing about this).

**Comment by w0lfschild** [comment]
The wiki has been updated with info to re-enable `System Integrity`

https://github.com/MacEnhance/MacForge/wiki/Uninstallation
