### ISSUE TITLE
Add csrutil command to readme

### ISSUE THREAD

**Issue by schroef** [MacEnhance/MacForge#46]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**
The initial command we need to enter isn't enough and we need to enter another command when booted using CMD+R. The small annoying thing is that isn't stated on this readme and we need hunt it down.

**Describe alternatives you've considered**
 I think it's more convenient for users if this was on your GitHub readme or site.

**Teachability, Documentation, Adoption, Migration Strategy**
--

**Comment by w0lfschild** [comment]
Sure, that can be added.

**Comment by w0lfschild** [comment]
It is done.
