### ISSUE TITLE
Dock crashing repeatedly on Big Sur (Black Screen, No Dock).

### ISSUE THREAD

**Issue by Arobasefr** [MacEnhance/MacForge#50]
when Macforge (1.08) with _colorfulSidebarX.bundle 2.2.0_is active I have  blackscreen with no access to bottom dock and inactiv window color buttons !

# v1 Regression

**Potential Commit/PR that introduced the regression**
If you have time to investigate, what PR/date introduced this issue.

**Describe the regression**
A clear and concise description of what the regression is.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Screenshots**

**Environment**
- MacForge version(s): [e.g. v0.10.1]
- OS version: [e.g. macOS 10.13.4]
- Plugins: [e.g. cleanHUD]

**Possible Solution**

**Additional context**

**Comment by w0lfschild** [comment]
Add the Dock to the Blacklist until and update is released.

The Dock is located here `/System/Library/CoreServices/Dock.app`

**Comment by Arobasefr** [comment]
> Add the Dock to the Blacklist until and update is released.
> 
> The Dock is located here `/System/Library/CoreServices/Dock.app`

Thank you very much for your reply. It's OK now :)

**Comment by w0lfschild** [comment]
Version 1.1.0 should fix this issue.

**Comment by jcameronjeff** [comment]
Im still experiemcing this issue. V1.1.0 on Mac OS 11.2

**Comment by Arobasefr** [comment]
Hello,
I had to Blacklist Dropbox.app because Dropbox disappared after boot.
Mac OS 11.2.1 with MAcForge v1.1.0

**Comment by w0lfschild** [comment]
@jcameronjeff Do you have crash logs?

@Arobasefr That's what the blacklist is there for.
