### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by yan-kisen** [MacEnhance/MacForge#51]
Dude,
You are a beast!

Thank you so much for your amazing work over the years.

I couldn't imagine using MacOS without your sweet tweaks!

Really, just wow...

(This was my only way to tell you that)

Also, this Twitter link is broken but I doubt that you care  🤙

![macforge-wg-screeenshot](https://user-images.githubusercontent.com/1116995/99782849-b193d680-2ae7-11eb-92db-64d67c422fb9.png)

**Comment by w0lfschild** [comment]
Thanks for the support 🙌

I'm working on overhauling the site but thanks for point that out. Easy to miss little things like that.
