### ISSUE TITLE
Explain Security Implications

### ISSUE THREAD

**Issue by dpren** [MacEnhance/MacForge#54]
Could we add a section to the README that briefly explains what security one sacrifices by disabling System Integrity Protection and Library Validation? How partially is it being disabled? Does it need to stay disabled? What kind of risk are you taking on by doing this?

This tool is awesome, but I'm unlikely to use it without understanding the tradeoffs. Thanks :)

**Comment by w0lfschild** [comment]
While I don't honestly think I can well describe the security implications to someone without the tech understanding to already know I've tried my best here:

[Link](https://www.macenhance.com/blog/2020/sip-sec)
