### ISSUE TITLE
SpacesRenamer and MacForge no longer work after upgraded to macOS Big Sur 11.1

### ISSUE THREAD

**Issue by amhammo** [MacEnhance/MacForge#55]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

For several minutes after MacForge is opened, mission control/hot corners/function keys stop working. I have SpacesRenamer installed, and that no longer works at all since updating my OS to Big Sur 11.1. 

**To Reproduce**

Just open SpacesRenamer and MacForge. No error message appears. 

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

I expect it to work correctly. 

**Screenshots**

![image](https://user-images.githubusercontent.com/43356898/104632998-84d5e880-566c-11eb-9d85-86a561c47c11.png)
SpacesRenamer cannot actually work. The "Update Names" button cannot be clicked.

![image](https://user-images.githubusercontent.com/43356898/104634329-78eb2600-566e-11eb-9df6-d3e72cdb0cb4.png)

I think I have all the correct things enabled/disabled to allow the programs to function correctly.

**Environment**
- MacForge version(s): v0.14.2 (2846)
- OS version:  macOS 11.1 Big Sur
- Plugins: SpacesRenamer

**Possible Solution**

**Additional context**

**Comment by w0lfschild** [comment]
Update MacForge. You can get the latest versions here [macenhance.com](https://www.macenhance.com/macforge)

**Comment by amhammo** [comment]
Thank you for redirecting me. I kept checking for updates in the old app and it said it was up-to-date. Still had to uninstall/reinstall/restart a couple times, but now it's working! Just donated, thank you again so much!

**Comment by w0lfschild** [comment]
No problem 0.X didn't update to 1.X because of some changes I made but in the future the app should keep itself up to date. If it ever doesn't the website is the best place to check.
