### ISSUE TITLE
Disable SIP only fs and debug section on BigSur.

### ISSUE THREAD

**Issue by r-plus** [MacEnhance/MacForge#60]
Hi @w0lfschild, this is just information, please close when you read.

I read your blog post https://www.macenhance.com/blog/2020/bigsur.html about broken `--without debug` option about SIP and confirm it on BigSur.

I found the workaround to disable SIP feature only for `fs` and `debug` on BigSur by `csrutil disable --with kext --with dtrace --with nvram --with basesystem`. This is works well.

result on BigSur 11.2.1:

```
$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

Refs:
- https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#how-do-i-disable-system-integrity-protection
- https://apple.stackexchange.com/questions/411598/what-are-the-potential-consequences-of-partially-disabling-sip-for-yabai

Thanks.

**Comment by w0lfschild** [comment]
Thanks for the feedback

The real workaround is to accept that if you've turned off the debug+filesystem restriction of SIP having the other options on really does essentially nothing in terms of security.

Also I submitted the issue as a bug to Apple a few months back and it has been fixed in macOS 11.3

Future releases of MacForge will simply instruct users to use `csrutil disable`.

**Comment by r-plus** [comment]
okey, it is simple :)

**Comment by w0lfschild** [comment]
> okey, it is simple :)

Yeah I'll probably add it into the documentation next time I update my website. Once again, thanks for the feedback.

**Comment by GJRobert** [comment]
Pardon me to use this as a asking board. If I ever need to enable SIP again to use certain macOS functions (e.g. to execute iOS apps from App Store, where it asks for higher system integrity and security), what command can I use in Recovery to meet macOS requirements while still maintain the usability of MacForge?
